export const skillIcons: Record<string, string> = {
  Python: "🐍",
  JavaScript: "⚡",
  TypeScript: "🔷",
  SQL: "🗄️",
  "C++": "⚙️",
  "React.js": "⚛️",
  "Next.js": "▲",
  "Tailwind CSS": "🎨",
  "Node.js": "🟢",
  "Express.js": "🚂",
  Flask: "🧪",
  FastAPI: "🚀",
  "REST APIs": "🔗",
  "JWT Auth": "🔐",
  PostgreSQL: "🐘",
  MySQL: "🐬",
  MongoDB: "🍃",
  Firebase: "🔥",
  Prisma: "◆",
  Docker: "🐳",
  Kubernetes: "☸️",
  "Red Hat OpenShift": "🎩",
  "AWS S3": "☁️",
  "GitHub Actions": "🔁",
  TensorFlow: "🧠",
  Keras: "🧩",
  OpenCV: "👁️",
  Pandas: "🐼",
  NumPy: "🔢",
};
